create table t_app(
	appid int auto_increment primary key,
	 imsi varchar(50) not null,
	 recorddate varchar(50) not null,
	 cellid varchar(50) not null,
	 curTxBytes double not null,
	 rsrp double not null,
	 deviceBrand varchar(20) not null,
	 memUsed double not null,
	 memTotal double not null,
     imei varchar(50) not null,
	 sinr double not null,
	 rssi double not null,
	 androidVersion varchar(20) not null,
	 cellId_n varchar(20) not null,
	 deviceModel varchar(20) not null,
	 mcc varchar(20) not null,
	 curRxBytes varchar(30) not null,
	 ci varchar(20) not null,
	 networkType varchar(50) not null,
	 pci varchar(20) not null,
	 cpuRate double not null,
	 enodbId varchar(50) not null,
	 tac varchar(20) not null,
	 longitude varchar(20) not null,
	 addr varchar(100) not null,
	 appName varchar(50) not null,
	 mnc varchar(30) not null,
	 operator varchar(50) not null,
	 pkgName varchar(50) not null,
	 latitude varchar(50) not null,
	 uid varchar(20) not null,
	 rsrq double not null,
	 sendrate double not null,
	 receiverate double not null,
	 memoryrate double not null,
	 omcid int not null
);
